// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaveIsland.ApiService.Infrastructure.Persistence;

#nullable disable

namespace RaveIsland.ApiService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624050755_AddStripeBilling")]
    partial class AddStripeBilling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtistTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("PrimaryGenreId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SocialLinksJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("StageName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtistTypeId");

                    b.HasIndex("PrimaryGenreId");

                    b.HasIndex("TenantId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.CheckInLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("GateId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScannedByName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ScannedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketId");

                    b.ToTable("CheckInLogs");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventArtist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrimaryGenreId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("SetEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("SetStart")
                        .HasColumnType("time without time zone");

                    b.Property<string>("StageNameOverride")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("PrimaryGenreId");

                    b.HasIndex("EventId", "ArtistId")
                        .IsUnique();

                    b.ToTable("EventArtists");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgeRestrictionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CancellationPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EntryPolicy")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("EventCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrganizerReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("PrimaryGenreId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProhibitedItems")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SecondaryGenreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SoundSystem")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TermsAndConditions")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Theme")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VenueTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisibilityTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgeRestrictionId");

                    b.HasIndex("CancellationPolicyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventCategoryId");

                    b.HasIndex("EventStatusId");

                    b.HasIndex("PrimaryGenreId");

                    b.HasIndex("SecondaryGenreId");

                    b.HasIndex("Slug");

                    b.HasIndex("TenantId");

                    b.HasIndex("VenueTypeId");

                    b.HasIndex("VisibilityTypeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventLookupSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("LookupTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("LookupValueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LookupValueId");

                    b.HasIndex("EventId", "LookupValueId")
                        .IsUnique();

                    b.ToTable("EventLookupSelections");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventMedia");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventPromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliesToTicketTypeIdsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Code")
                        .IsUnique();

                    b.ToTable("EventPromoCodes");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("GatesOpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("LastEntryTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "DayNumber")
                        .IsUnique();

                    b.ToTable("EventSchedules");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventTicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultLookupValueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxPerUser")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SaleEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SaleStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefaultLookupValueId");

                    b.HasIndex("EventId");

                    b.ToTable("EventTicketTypes");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LookupTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110001"),
                            Code = "EventCategory",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Categories for classifying events",
                            IsSystem = true,
                            Name = "Event Category"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110002"),
                            Code = "MusicGenre",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Music genres for events and artists",
                            IsSystem = true,
                            Name = "Music Genre"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110003"),
                            Code = "VenueType",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Types of event venues",
                            IsSystem = true,
                            Name = "Venue Type"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110004"),
                            Code = "Facility",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Event facilities and amenities",
                            IsSystem = true,
                            Name = "Facility"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110005"),
                            Code = "ProductionFeature",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Production and visual features",
                            IsSystem = true,
                            Name = "Production Feature"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110006"),
                            Code = "TicketType",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default ticket type labels",
                            IsSystem = true,
                            Name = "Ticket Type"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110007"),
                            Code = "AgeRestriction",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Age restrictions for events",
                            IsSystem = true,
                            Name = "Age Restriction"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110008"),
                            Code = "EventVisibility",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Event visibility types",
                            IsSystem = true,
                            Name = "Event Visibility"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111110009"),
                            Code = "EventStatus",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Event lifecycle statuses",
                            IsSystem = true,
                            Name = "Event Status"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-11111111000a"),
                            Code = "PaymentMethod",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Supported payment methods",
                            IsSystem = true,
                            Name = "Payment Method"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-11111111000b"),
                            Code = "District",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sri Lanka districts",
                            IsSystem = true,
                            Name = "District"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-11111111000c"),
                            Code = "ArtistType",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Types of performers",
                            IsSystem = true,
                            Name = "Artist Type"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-11111111000d"),
                            Code = "SocialMediaProvider",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Social media platforms",
                            IsSystem = true,
                            Name = "Social Media Provider"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-11111111000e"),
                            Code = "CancellationPolicy",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Refund and cancellation policies",
                            IsSystem = true,
                            Name = "Cancellation Policy"
                        });
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LookupTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LookupTypeId", "Code")
                        .IsUnique();

                    b.ToTable("LookupValues");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.StripeWebhookEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("StripeWebhookEvents");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BillingSetupCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PendingPromotionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StripeSubscriptionStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StripeCustomerId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "KeycloakUserId")
                        .IsUnique();

                    b.ToTable("TenantMemberships");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventTicketTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("HolderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HolderName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsCheckedIn")
                        .HasColumnType("boolean");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventTicketTypeId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IntendedRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KeycloakUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("TenantId", "Email");

                    b.ToTable("UserInvitations");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LandmarkInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Province")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Artist", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "ArtistType")
                        .WithMany()
                        .HasForeignKey("ArtistTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "PrimaryGenre")
                        .WithMany()
                        .HasForeignKey("PrimaryGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistType");

                    b.Navigation("PrimaryGenre");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.CheckInLog", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Ticket", "Ticket")
                        .WithMany("CheckInLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventArtist", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Artist", "Artist")
                        .WithMany("EventArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany("Artists")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "PrimaryGenre")
                        .WithMany()
                        .HasForeignKey("PrimaryGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artist");

                    b.Navigation("Event");

                    b.Navigation("PrimaryGenre");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "AgeRestriction")
                        .WithMany()
                        .HasForeignKey("AgeRestrictionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "CancellationPolicy")
                        .WithMany()
                        .HasForeignKey("CancellationPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "EventCategory")
                        .WithMany()
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "EventStatus")
                        .WithMany()
                        .HasForeignKey("EventStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "PrimaryGenre")
                        .WithMany()
                        .HasForeignKey("PrimaryGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "SecondaryGenre")
                        .WithMany()
                        .HasForeignKey("SecondaryGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany("Events")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "VenueType")
                        .WithMany()
                        .HasForeignKey("VenueTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "VisibilityType")
                        .WithMany()
                        .HasForeignKey("VisibilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeRestriction");

                    b.Navigation("CancellationPolicy");

                    b.Navigation("EventCategory");

                    b.Navigation("EventStatus");

                    b.Navigation("PrimaryGenre");

                    b.Navigation("SecondaryGenre");

                    b.Navigation("Tenant");

                    b.Navigation("VenueType");

                    b.Navigation("VisibilityType");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventLookupSelection", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany("LookupSelections")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "LookupValue")
                        .WithMany()
                        .HasForeignKey("LookupValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("LookupValue");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventMedia", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany("Media")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventPromoCode", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany("PromoCodes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventSchedule", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany("Schedules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventTicketType", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "DefaultLookupValue")
                        .WithMany()
                        .HasForeignKey("DefaultLookupValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultLookupValue");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupType", "LookupType")
                        .WithMany("Values")
                        .HasForeignKey("LookupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupType");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.TenantMembership", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Ticket", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventTicketType", "EventTicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("EventTicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventTicketType");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.UserInvitation", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany("Invitations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Venue", b =>
                {
                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupValue", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", "Event")
                        .WithOne("Venue")
                        .HasForeignKey("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Venue", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Artist", b =>
                {
                    b.Navigation("EventArtists");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventEntity", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("LookupSelections");

                    b.Navigation("Media");

                    b.Navigation("PromoCodes");

                    b.Navigation("Schedules");

                    b.Navigation("TicketTypes");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.EventTicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.LookupType", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Tenant", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Invitations");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("RaveIsland.ApiService.Infrastructure.Persistence.Entities.Ticket", b =>
                {
                    b.Navigation("CheckInLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
