namespace RaveIsland.ApiService.Infrastructure.Lookups;

public static class LookupSeedData
{
    public static IReadOnlyList<LookupSeedTypeDefinition> Types { get; } =
    [
        new(LookupTypeIds.EventCategory, LookupTypeCodes.EventCategory, "Event Category", "Categories for classifying events",
        [
            new("Rave", "Rave", 1),
            new("Techno", "Techno", 2),
            new("House", "House", 3),
            new("Trance", "Trance", 4),
            new("EDMFestival", "EDM Festival", 5),
            new("BeachParty", "Beach Party", 6),
            new("AfterParty", "After Party", 7),
            new("WarehouseParty", "Warehouse Party", 8),
        ]),
        new(LookupTypeIds.MusicGenre, LookupTypeCodes.MusicGenre, "Music Genre", "Music genres for events and artists",
        [
            new("Techno", "Techno", 1),
            new("MelodicTechno", "Melodic Techno", 2),
            new("House", "House", 3),
            new("DeepHouse", "Deep House", 4),
            new("AfroHouse", "Afro House", 5),
            new("ProgressiveHouse", "Progressive House", 6),
            new("Trance", "Trance", 7),
            new("Psytrance", "Psytrance", 8),
            new("Hardstyle", "Hardstyle", 9),
            new("DrumAndBass", "Drum & Bass", 10),
            new("Dubstep", "Dubstep", 11),
        ]),
        new(LookupTypeIds.VenueType, LookupTypeCodes.VenueType, "Venue Type", "Types of event venues",
        [
            new("Beach", "Beach", 1),
            new("Hotel", "Hotel", 2),
            new("Warehouse", "Warehouse", 3),
            new("NightClub", "Night Club", 4),
            new("Forest", "Forest", 5),
            new("Villa", "Villa", 6),
            new("Rooftop", "Rooftop", 7),
            new("OpenGround", "Open Ground", 8),
        ]),
        new(LookupTypeIds.Facility, LookupTypeCodes.Facility, "Facility", "Event facilities and amenities",
        [
            new("Parking", "Parking", 1),
            new("FoodCourt", "Food Court", 2),
            new("Bar", "Bar", 3),
            new("VIPArea", "VIP Area", 4),
            new("SmokingArea", "Smoking Area", 5),
            new("Camping", "Camping", 6),
            new("MedicalTeam", "Medical Team", 7),
            new("Lockers", "Lockers", 8),
            new("ChargingStations", "Charging Stations", 9),
            new("Restrooms", "Restrooms", 10),
            new("SecurityTeam", "Security Team", 11),
        ]),
        new(LookupTypeIds.ProductionFeature, LookupTypeCodes.ProductionFeature, "Production Feature", "Production and visual features",
        [
            new("LEDWall", "LED Wall", 1),
            new("Lasers", "Lasers", 2),
            new("Pyrotechnics", "Pyrotechnics", 3),
            new("CO2Cannons", "CO2 Cannons", 4),
            new("DroneShow", "Drone Show", 5),
            new("FireShow", "Fire Show", 6),
            new("VisualMapping", "Visual Mapping", 7),
        ]),
        new(LookupTypeIds.TicketType, LookupTypeCodes.TicketType, "Ticket Type", "Default ticket type labels",
        [
            new("GeneralAdmission", "General Admission", 1),
            new("EarlyBird", "Early Bird", 2),
            new("Phase1", "Phase 1", 3),
            new("Phase2", "Phase 2", 4),
            new("VIP", "VIP", 5),
            new("VVIP", "VVIP", 6),
            new("Backstage", "Backstage", 7),
            new("Crew", "Crew", 8),
        ]),
        new(LookupTypeIds.AgeRestriction, LookupTypeCodes.AgeRestriction, "Age Restriction", "Age restrictions for events",
        [
            new("AllAges", "All Ages", 1),
            new("18Plus", "18+", 2),
            new("21Plus", "21+", 3),
            new("25Plus", "25+", 4),
        ]),
        new(LookupTypeIds.EventVisibility, LookupTypeCodes.EventVisibility, "Event Visibility", "Event visibility types",
        [
            new("Public", "Public", 1),
            new("Private", "Private", 2),
            new("InviteOnly", "Invite Only", 3),
            new("Hidden", "Hidden", 4),
        ]),
        new(LookupTypeIds.EventStatus, LookupTypeCodes.EventStatus, "Event Status", "Event lifecycle statuses",
        [
            new("Draft", "Draft", 1),
            new("PendingApproval", "Pending Approval", 2),
            new("Published", "Published", 3),
            new("SoldOut", "Sold Out", 4),
            new("Postponed", "Postponed", 5),
            new("Cancelled", "Cancelled", 6),
            new("Completed", "Completed", 7),
        ]),
        new(LookupTypeIds.PaymentMethod, LookupTypeCodes.PaymentMethod, "Payment Method", "Supported payment methods",
        [
            new("Card", "Card", 1),
            new("PayHere", "PayHere", 2),
            new("Genie", "Genie", 3),
            new("FriMi", "FriMi", 4),
            new("BankTransfer", "Bank Transfer", 5),
            new("Cash", "Cash", 6),
        ]),
        new(LookupTypeIds.District, LookupTypeCodes.District, "District", "Sri Lanka districts",
        [
            new("Colombo", "Colombo", 1),
            new("Gampaha", "Gampaha", 2),
            new("Kalutara", "Kalutara", 3),
            new("Galle", "Galle", 4),
            new("Matara", "Matara", 5),
            new("Hambantota", "Hambantota", 6),
            new("Kandy", "Kandy", 7),
            new("Matale", "Matale", 8),
            new("NuwaraEliya", "Nuwara Eliya", 9),
            new("Jaffna", "Jaffna", 10),
            new("Kilinochchi", "Kilinochchi", 11),
            new("Mannar", "Mannar", 12),
            new("Vavuniya", "Vavuniya", 13),
            new("Mullaitivu", "Mullaitivu", 14),
            new("Batticaloa", "Batticaloa", 15),
            new("Ampara", "Ampara", 16),
            new("Trincomalee", "Trincomalee", 17),
            new("Kurunegala", "Kurunegala", 18),
            new("Puttalam", "Puttalam", 19),
            new("Anuradhapura", "Anuradhapura", 20),
            new("Polonnaruwa", "Polonnaruwa", 21),
            new("Badulla", "Badulla", 22),
            new("Monaragala", "Monaragala", 23),
            new("Ratnapura", "Ratnapura", 24),
            new("Kegalle", "Kegalle", 25),
        ]),
        new(LookupTypeIds.ArtistType, LookupTypeCodes.ArtistType, "Artist Type", "Types of performers",
        [
            new("DJ", "DJ", 1),
            new("LiveBand", "Live Band", 2),
            new("MC", "MC", 3),
            new("Performer", "Performer", 4),
            new("Dancer", "Dancer", 5),
            new("VJ", "VJ", 6),
            new("VisualArtist", "Visual Artist", 7),
        ]),
        new(LookupTypeIds.SocialMediaProvider, LookupTypeCodes.SocialMediaProvider, "Social Media Provider", "Social media platforms",
        [
            new("Facebook", "Facebook", 1),
            new("Instagram", "Instagram", 2),
            new("TikTok", "TikTok", 3),
            new("YouTube", "YouTube", 4),
            new("Spotify", "Spotify", 5),
            new("SoundCloud", "SoundCloud", 6),
            new("Telegram", "Telegram", 7),
            new("Discord", "Discord", 8),
        ]),
        new(LookupTypeIds.CancellationPolicy, LookupTypeCodes.CancellationPolicy, "Cancellation Policy", "Refund and cancellation policies",
        [
            new("NoRefunds", "No Refunds", 1),
            new("24HourRefund", "24 Hour Refund", 2),
            new("48HourRefund", "48 Hour Refund", 3),
            new("7DayRefund", "7 Day Refund", 4),
            new("OrganizerApprovalRequired", "Organizer Approval Required", 5),
        ]),
    ];
}
